'See project' popup
Salimer/old-Portfolio pull request #12
Opened 2023-04-11 23:29 UTC by Salimer

In this branch I : 

- Added the detail popup for the mobile version 
- Added the detail popup for the desktop version
- Set the array with the projects' objects

2023-04-11 23:49 UTC, brainconnect93 reviewed
Hi @Salimer,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://camo.githubusercontent.com/999c41ff216bced575a5c7873c1c4ed04ef945c867ca87788003794670ee5aa7/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f785550476377453343556b586c766f6e75672f67697068792e676966">

## Invalid Code Review Request

- [ ] You have submitted a project that has Linters failing in it

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

_Cheers and Happy coding!👏👏👏_

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

-----

_Invalid Code Review Request does not count into the code reviews limit._

2023-04-12 00:14 UTC, addod19 commented
### Hi @Salimer, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the project lacks commits from both partners since this is a pair programming activity

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 00:17 UTC, Salimer commented
@addod19 brother all the checks are Green. Could you please check again

2023-04-12 00:41 UTC, addod19 commented
### Hi @Salimer, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because the project lacks commits from both partners since this is a pair programming activity

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-12 09:59 UTC, codecaiine requested changes
Hi @Salimer and partner, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Great pop UI design ✔️ 
- Good array of object implementation ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 09:59 UTC, codecaiine commented on index.html
> +             </div>
- [ ] Good job so far 👏 But I have some issues with your pop as you can see on the video link shared with you below ⬇️ we can not see the top of the popup windows because of your overflow which makes it impossible for the user to click (or taps) the close (X) button to make popup disappear. Please fix it in order to make your pop work as expected 👍
 https://www.loom.com/share/d541ff9e50b046b5b81573b851c75479

2023-04-12 12:14 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @Salimer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 12:14 UTC, Qoosim commented on worksSectionRefactor.js
> +  // Append the container element to the div with class "works"
- [OPTIONAL] Great job implementing the request from the previous reviewer. You've done a great job. I would also recommend you the look into the alignment of the two buttons below the image on the popup window to look like how they appear on the figma design. You might also need to reduce the width of the popup window in order to properly match the guiding template. You can actually make your popup window to contain all the information at one glance without the users need to scroll for the rest of the info. You can give it a shot and see how it goes. Great job brother. :handshake:

### Your Design
![your-design](https://user-images.githubusercontent.com/26597432/231452402-97fba7ae-bcb5-4df4-ba1f-b70f3395eda2.png)

### Figma Design 
![temp-design](https://user-images.githubusercontent.com/26597432/231452436-b19c6f73-528d-48f0-aaa5-25966a04bc02.png)

2023-04-12 12:35 UTC, merged