Accessbility checkup
Salimer/old-Portfolio pull request #9
Opened 2023-04-03 16:35 UTC by Salimer

In this branch I improved the accessibility of my website by performing the following fixes: 

In page titles I :
- Updated the title to adequately and briefly describe the page's content.

[Image text alternatives** (<img alt="alt text”>)](https://www.w3.org/WAI/test-evaluate/preliminary/#images):
- Updated the logo image element to adequately and briefly describe the image's content.
- Added the ITA to social media icons
- Added the image text alternative to the image element of the nav to adequately and briefly describes the content of the image.
- Updated the bottom-arrow image element to adequately and briefly describe the image's content.
- Added the ITA to the technologies’ cards icons
 
Text headings
- Update text headings to match The heading hierarchy is meaningful. 

Color contrast - no issues found

Resize - no issues found

Interaction
- Added labels to form elements

Moving content - no issues found

Multimedia - no issues found 

The basic structure of the page - no issues found

2023-04-03 17:28 UTC, AdnanOlarmmi requested changes
Hi @Salimer, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice UI design.
- Good structure.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- [ ] Kindly follow semantic HTML guidelines in your code 🙃.
You should have something like this instead of repetitive `div`s this enhances SEOs.
```
<body>
  <header>
    <nav>
    <nav>
  </header>
  
  <main>
    <section>
    </section>
    <article>
    </article>
  </main>
  
  <footer>
    <section>
    </section>
  </footer>
</body>
```

check this [link](https://web.dev/learn/html/semantic-html/) to read, know and learn more about semantic HTML. 💯 😀.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403180958.html
> +    <title>Portfolio</title>
- [ ] Kindly note that the title should satisfactorily and succinctly describe the page's content. As an example:
Bad titles:
My portfolio.
Portfolio.


Improved page titles:
John's Portfolio
John Front-end web developer

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403180958.html
> +            <img class="Normal-Button" src="Assets/nav.svg">
- [ ] Kindly include an `alt` attribute here, indicating to a screen reader and a visually impaired person that this is a nav bar.

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403180958.html
> +                <li><a href="https://www.linkedin.com/in/salim-bamahfoodh-707b74200/"><img src="Assets/Linkedin icon.svg"></a></li>
- [ ] Kindly include an `alt` attribute here, indicating to a screen reader and a visually impaired person what the image entails.

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403180958.html
> +                <li><a href="https://www.linkedin.com/in/salim-bamahfoodh-707b74200/"><img src="Assets/Linkedin icon.svg"></a></li>
- [ ] Kindly include an `alt` attribute here, indicating to a screen reader and a visually impaired person what the image entails.

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403180958.html
> +            <li><a href="https://www.linkedin.com/in/salim-bamahfoodh-707b74200/"><img src="Assets/Linkedin icon.svg"></a></li>
- [ ] Kindly include an `alt` attribute here, indicating to a screen reader and a visually impaired person what the image entails.

2023-04-03 17:28 UTC, AdnanOlarmmi commented on .history/index_20230403181545.html
> +                <img src="Assets/bottom arrow.svg" alt="disabled" width="40px" height="40px">
- [ ] For these kinds, you should specify what type of image they are not to cause ambiguity for screen readers and visually impaired persons 😃. for example "Project Image" or more explanatory like "Calculator Project Image" or "Google clone project snippet".

This is applicable to all ambiguous image `alt` attributes not just this 😉.

- If not adding an `alt` won't affect screen readers kindly make the value for `alt` as `null`.

2023-04-04 08:31 UTC, waelelsafty07 commented
Hello @AdnanOlarmmi I'm a coding partner of @Salimer  
  You reviewed wrong file on [.history/index_20230403180958.html](https://github.com/Salimer/Portfolio/pull/9/files/ffa8c467f867a5762a85a198ce66bfa6a35e964a#diff-508d513507639581e3b70dec9414b625eb70e6921ec58a7e03d3ee4c4a9a4f0a) and this is old version 
you should have reviewed [index.html](https://github.com/Salimer/Portfolio/pull/9/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051).
All required changes are implemented in [index.html](https://github.com/Salimer/Portfolio/pull/9/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051) before @Salimer requested a review yesterday

2023-04-04 09:15 UTC, AdnanOlarmmi commented
Hi @waelelsafty07 and @Salimer, My bad for making such mistake, kindly fix the changes applicable to the current file and ask for a re-review 😊

2023-04-04 09:29 UTC, OyePriscilla approved these changes
Hi @Salimer 👏 👏 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Descriptive page title ✔️ 
Add alt attributes for images ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-04 09:29 UTC, OyePriscilla commented on index.html
> +                <img src="Assets/bottom arrow.svg" alt="bottom-arrow" width="40px" height="40px">
- [optionally] Kindly keep all inline styling in a separate CSS file according to the best practices. 👍

2023-04-04 09:32 UTC, merged